simpleERP/crud/urls.py
from django.urls import path
from .views import InvoiceListView, InvoiceCreateView, InvoiceEditView, ProductCreateView

app_name='crud'

urlpatterns = [
    # Invoices
    path('create-invoice/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/<int:pk>/update/', InvoiceEditView.as_view(), name="invoice_edit"),
    path('list/', InvoiceListView.as_view(), name='invoice_list'),

    # Products
    path('create-product/', ProductCreateView.as_view(), name='product_create'),
]

simpleERP/simpleERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='login')),
    path('crud/', include('crud.urls', namespace='crud_list'))
]

simpleERP/users/urls.py
from django.urls import path
from . import views

app_name='login'

urlpatterns = [
    path('', views.loginView, name='login_join'),
    path('register/', views.registerView, name='login_register'),    
]

simpleERP/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator
from django.utils import timezone

class User(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(
        _('email address'), 
        unique=True,
        blank=False,
        validators=[EmailValidator()],
        error_messages={
            'unique': _("A user with that email already exists."),
        }
    )
    
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'),  default=timezone.now)
    last_updated = models.DateTimeField(_('last updated'), auto_now=True)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['-date_joined']
    
    def __str__(self):
        return self.get_full_name() or self.email

simpleERP/users/forms.py
from django import forms 
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

simpleERP/users/views.py
import logging
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.messages import get_messages
from .models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password

logger = logging.getLogger(__name__)

# Create your views here.
def loginView(request):
    storage = get_messages(request)
    list(storage)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not username or not password:
            messages.error(request, 'Por favor ingrese ambos campos')
            logger.warning('Intento de login con campos vacíos')
            return render(request, 'login.html')
        
        User = get_user_model()

        try:
            user = User.objects.get(username=username)
            if check_password(password, user.password):  # Comparación segura
                auth_login(request, user)
                return redirect('crud:invoice_list')
            else:
                messages.error(request, 'Credenciales incorrectas!')
                logger.warning(f'Contraseña incorrecta para el usuario: {username}')
        except User.DoesNotExist:
            messages.error(request, 'Usuario no existe')
            logger.warning(f'Intento de login con usuario inexistente: {username}')
            
        except Exception as e:
            messages.error(request, 'Error en el sistema')
            logger.error(f'Error durante el login: {str(e)}', exc_info=True)

    return render(request, 'login.html', {'messages': messages.get_messages(request)})

def registerView(request):
    first_name = ""
    last_name = ""
    username = ""
    password = ""
    email = ""
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        if not User.objects.filter(username=username).exists():
            newUser = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, password=password, email=email)
            newUser.save()
            return redirect('login:login_join')
        else:
            messages.error(request, 'Usuario ya existe!')
            return render(request, 'register.html')
    else:
        return render(request, 'register.html', {'message': 'Credenciales incorrectas!'})

simpleERP/users/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <title>LOGIN</title>
    </head>
    <body>
        <section class="vh-100">
            <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">
        
                <div class="px-5 ms-xl-4">
                    <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                    <span class="h1 fw-bold mb-0">Logo</span>
                </div>
        
                <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
        
                    <form method="POST" style="width: 23rem;">
                        {% csrf_token %}
        
                        <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Inicio de sesión</h3>
                        
                        {% if messages %}
                            <div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
                                {% for message in messages %}
                                <div id="toastMessage" class="toast align-items-center text-bg-{% if message.tags == 'error' %}danger{% else %}success{% endif %} border-0"
                                    role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
                                    <div class="d-flex">
                                        <div class="toast-body">
                                            {{ message }}
                                        </div>
                                        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div data-mdb-input-init class="form-outline mb-4">
                            <label class="form-label" for="username">Nombre de usuario</label>
                            <input type="username" name="username" id="username" class="form-control form-control-lg" />
                        </div>
            
                        <div data-mdb-input-init class="form-outline mb-4">
                            <label class="form-label" for="password">Contraseña</label>
                            <input type="password" name="password" id="password" class="form-control form-control-lg" />
                        </div>
                
                        <div class="pt-1 mb-4">
                            <button data-mdb-button-init data-mdb-ripple-init class="btn btn-info btn-lg btn-block" type="submit">Iniciar Sesión</button>
                        </div>
                        <p class="small mb-5 pb-lg-2"><a class="text-muted" href="#!">¿Has olvidado la contraseña?</a></p>
                        {% url 'login:login_register' as urlRegister %}
                        <p>¿No tienes cuenta? <a href="{{urlRegister}}" class="link-info">Registrate aquí!</a></p>
        
                    </form>
        
                </div>
        
                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                    alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
                </div>
            </div>
            </div>
        </section>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var toastElList = [].slice.call(document.querySelectorAll('.toast'));
                if (toastElList.length > 0) {  // Solo si hay mensajes
                    toastElList.forEach(function(toastEl) {
                        var toast = new bootstrap.Toast(toastEl);
                        toast.show();
                    });
                }
            });
        </script>
    </body>
</html>

simpleERP/users/templates/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <title>REGISTER</title>
    </head>
    <body>
        <section class="vh-100">
            <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">
        
                    <div class="px-3 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0">Logo</span>
                    </div>
            
                    <div class="d-flex align-items-center h-custom-2 px-2 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
                        <!-- Toast Container -->
                        {% if messages %}
                        <div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
                            {% for message in messages %}
                            <div class="toast align-items-center text-bg-{% if message.tags == 'error' %}danger{% else %}success{% endif %} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                                <div class="d-flex">
                                <div class="toast-body">
                                    {{ message }}
                                </div>
                                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                                                
                        <form method="POST" style="width: 100%; height: 100%;">
                            {% csrf_token %}
            
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Registrate</h3>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="name">Nombre</label>
                                        <input type="text" name="first_name" id="first_name" class="form-control form-control-lg" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="username">Apellidos</label>
                                        <input type="text" name="last_name" id="last_name" class="form-control form-control-lg" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="username">Nombre de usuario</label>
                                        <input type="text" name="username" id="username" class="form-control form-control-lg" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="password">Contraseña</label>
                                        <input type="password" name="password" id="password" class="form-control form-control-lg" />
                                    </div>
                                </div>
                            </div>
                            
                            <div data-mdb-input-init class="form-outline mb-4">
                                <label class="form-label" for="email">Correo electronico</label>
                                <input type="text" name="email" id="email" class="form-control form-control-lg" />
                            </div>
                    
                            <div class="pt-1 mb-4">
                                <button data-mdb-button-init data-mdb-ripple-init class="btn btn-info btn-lg btn-block" type="submit">Registrar</button>
                                <input class="btn btn-danger btn-lg btn-block" type="reset" value="Cancelar">
                            </div>
            
                        </form>
            
                    </div>
        
                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                    alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
                </div>
            </div>
            </div>
        </section>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var toastEl = document.getElementById('toastMessage');
                if (toastEl.innerText.trim() !== "") {
                    var toast = new bootstrap.Toast(toastEl);
                    toast.show();
                }
            });
        </script>
    </body>
</html>